name: Report Bug
description: "Something doesn't work as expected or flat out crash."
body:
  - type: markdown
    attributes:
      value: "A bug/crash report with sufficient information and logs to reproduce and track down."
  - type: input
    id: version
    attributes:
      label: Mod Loader Version
      description: "Which version of the Cleanroom are you using?"
      placeholder: "Example: Cleanroom 0.2.4-alpha"
    validations:
      required: true
  - type: dropdown
    id: java
    attributes:
      label: Java Version
      description: What Java version are you using? Make sure you're not using an outdated major version like Java 8 and using latest minor version (e.g. Java 17.0.6 over 17.0.2)
      options:
        - Java 21
        - Java 22
        - Java 23
        - Java 24
        - Java 25 (Early Access)
        - Other (Please Specify)
    validations:
      required: true
  - type: textarea
    id: report
    attributes:
      label: Bug Report
      description: "Relevant information, as well as relevant logs attached such as `logs/latest.log` and `logs/debug.log`."
      placeholder: "Example: https://mclo.gs/ OR submit the file to github by dragging it to this textbox."
    validations:
      required: true
  - type: textarea
    id: modlist
    attributes:
      label: Mod List
      description: "List of mods, ideally a minimal reproducible set (can be retrieved from latest.log)."
      placeholder: "List of mods goes here"
    validations:
      required: true
  - type: checkboxes
    id: final
    attributes:
      label: Final Checklist
      description: Certify that you read things
      options:
        - label: "I have searched the issues and haven't found a similar issue."
          required: true
        - label: "This issue doesn't occur without this mod."
          required: true
        - label: |
            I did not use PCL/PCLCE or other unsupported launchers.
            我没有使用 PCL/PCLCE 等其他未被支持的启动器。
          required: true