name: Feature Request
description: "I want this feature in this mod right here, right now!"
title: "[Suggestion] "
labels: [suggestion]
body:
  - type: textarea
    attributes:
      label: The Suggestion
      description: Describe the idea you have for the mod. Include details such as what the feature would do or what aspect of the mod it improves.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why Should It Be in the Mod?
      description: Describe why you would like to see this idea in the mod. Include reasons such as how mod would be improved if this idea was implemented.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Please Read and Confirm the Following
      options:
        - label: I have confirmed this suggestion is unique and has not been suggested already.
          required: true